# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
        - name: my-application
          image: registry-url
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: mchregistry
---
# This section will create a service in the Kubernetes cluster so that the deployment can be accessed from the outside
apiVersion: v1
kind: Service
metadata:
  name: my-application
  namespace: dev
spec:
  selector:
    app: my-application
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer